package tablet.gui.dialog.prefs;

import java.awt.*;
import javax.swing.*;

import tablet.gui.*;

import scri.commons.gui.*;

class NBVisualizationPanel extends JPanel
{
	private DefaultComboBoxModel dnaModel;
	private DefaultComboBoxModel proteinModel;

	public NBVisualizationPanel()
    {
        initComponents();

        setBackground(Color.white);
        panel.setBackground(Color.white);

		panel.setBorder(BorderFactory.createTitledBorder(RB.getString("gui.dialog.prefs.NBVisualizationPanel.panelTitle")));

		RB.setText(dnaLabel, "gui.dialog.prefs.NBVisualizationPanel.dnaLabel");
		RB.setText(proteinLabel, "gui.dialog.prefs.NBVisualizationPanel.proteinLabel");

		dnaModel = new DefaultComboBoxModel();
        dnaModel.addElement("*");
		dnaModel.addElement("-");
        dnaCombo.setModel(dnaModel);
		dnaCombo.setSelectedIndex(Prefs.visPadCharType);

		proteinModel = new DefaultComboBoxModel();
        proteinModel.addElement(".");
		proteinModel.addElement("*");
        proteinCombo.setModel(proteinModel);
		proteinCombo.setSelectedIndex(Prefs.visStopCharType);
    }

	public void applySettings()
	{
		Prefs.visPadCharType = dnaCombo.getSelectedIndex();
		Prefs.visStopCharType = proteinCombo.getSelectedIndex();

		// This will force the visualization area to recreate its color schemes
		// which will change the rendered characters to their new states
		Tablet.winMain.getAssemblyPanel().forceRedraw();
		Tablet.winMain.getAssemblyPanel().repaint();
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        dnaLabel = new javax.swing.JLabel();
        dnaCombo = new javax.swing.JComboBox();
        proteinLabel = new javax.swing.JLabel();
        proteinCombo = new javax.swing.JComboBox();

        panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Display options:"));

        dnaLabel.setLabelFor(dnaCombo);
        dnaLabel.setText("Character to display for DNA pad/gap bases:");

        proteinLabel.setLabelFor(proteinCombo);
        proteinLabel.setText("Character to display for Protein stop codons:");

        org.jdesktop.layout.GroupLayout panelLayout = new org.jdesktop.layout.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelLayout.createSequentialGroup()
                .addContainerGap()
                .add(panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(panelLayout.createSequentialGroup()
                        .add(dnaLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(dnaCombo, 0, 99, Short.MAX_VALUE))
                    .add(panelLayout.createSequentialGroup()
                        .add(proteinLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(proteinCombo, 0, 99, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelLayout.createSequentialGroup()
                .addContainerGap()
                .add(panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(dnaLabel)
                    .add(dnaCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(proteinLabel)
                    .add(proteinCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(panel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(panel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox dnaCombo;
    private javax.swing.JLabel dnaLabel;
    private javax.swing.JPanel panel;
    private javax.swing.JComboBox proteinCombo;
    private javax.swing.JLabel proteinLabel;
    // End of variables declaration//GEN-END:variables
}