// Copyright 2009-2018 Information & Computational Sciences, JHI. All rights
// reserved. Use is subject to the accompanying licence terms.

package tablet.gui.dialog.prefs;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

import tablet.gui.*;
import static tablet.gui.ribbon.RibbonController.*;

import scri.commons.gui.*;

class VisualizationTabNB extends JPanel
{
	private DefaultComboBoxModel<String> dnaModel;
	private DefaultComboBoxModel<String> proteinModel;

	public VisualizationTabNB()
    {
        initComponents();

        TabletUtils.setPanelColor(this, false);
        TabletUtils.setPanelColor(panel1, false);
		TabletUtils.setPanelColor(panel2, false);

		// Top panel
		panel1.setBorder(BorderFactory.createTitledBorder(RB.getString("gui.dialog.prefs.NBVisualizationPanel.panel1Title")));

		RB.setText(dnaLabel, "gui.dialog.prefs.NBVisualizationPanel.dnaLabel");
		RB.setText(proteinLabel, "gui.dialog.prefs.NBVisualizationPanel.proteinLabel");
		RB.setText(padLabel, "gui.dialog.prefs.NBVisualizationPanel.padLabel");
		RB.setText(tagCheckbox, "gui.dialog.prefs.NBVisualizationPanel.tagCheckbox");

		dnaModel = new DefaultComboBoxModel<String>();
        dnaModel.addElement("*");
		dnaModel.addElement("-");
        dnaCombo.setModel(dnaModel);
		dnaCombo.setSelectedIndex(Prefs.visPadCharType);

		proteinModel = new DefaultComboBoxModel<String>();
        proteinModel.addElement(".");
		proteinModel.addElement("*");
        proteinCombo.setModel(proteinModel);
		proteinCombo.setSelectedIndex(Prefs.visStopCharType);

		padSpinner.getModel().setValue(Prefs.visPadReads);

		tagCheckbox.setSelected(Prefs.visNeverTagUnknownBases);
		tagCheckbox.setBorder(BorderFactory.createEmptyBorder(0, -2, 0, 0));


		// Bottom panel
		panel2.setBorder(BorderFactory.createTitledBorder(RB.getString("gui.dialog.prefs.NBVisualizationPanel.panel2Title")));
		RB.setText(bColors, "gui.dialog.prefs.NBVisualizationPanel.bColors");

		bColors.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e)
			{
				bandStyles.customizeColors();
			}
		});
    }

	public void applySettings()
	{
		Prefs.visPadCharType = dnaCombo.getSelectedIndex();
		Prefs.visStopCharType = proteinCombo.getSelectedIndex();
		Prefs.visPadReads = (Integer) padSpinner.getModel().getValue();
		Prefs.visNeverTagUnknownBases = tagCheckbox.isSelected();

		// This will force the visualization area to recreate its color schemes
		// which will change the rendered characters to their new states
		Tablet.winMain.getAssemblyPanel().forceRedraw();
		Tablet.winMain.getAssemblyPanel().repaint();
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        dnaLabel = new javax.swing.JLabel();
        dnaCombo = new javax.swing.JComboBox<String>();
        proteinLabel = new javax.swing.JLabel();
        proteinCombo = new javax.swing.JComboBox<String>();
        padSpinner = new javax.swing.JSpinner();
        padLabel = new javax.swing.JLabel();
        tagCheckbox = new javax.swing.JCheckBox();
        panel2 = new javax.swing.JPanel();
        bColors = new javax.swing.JButton();

        panel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Display options:"));

        dnaLabel.setLabelFor(dnaCombo);
        dnaLabel.setText("Character to display for DNA pad/gap bases:");

        proteinLabel.setLabelFor(proteinCombo);
        proteinLabel.setText("Character to display for Protein stop codons:");

        padSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        padLabel.setLabelFor(padSpinner);
        padLabel.setText("Allow at least the following base gap between reads:");

        tagCheckbox.setText("Dont' tag unknown, padded, or N bases as variants");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tagCheckbox)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(padLabel)
                            .addComponent(proteinLabel)
                            .addComponent(dnaLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(proteinCombo, javax.swing.GroupLayout.Alignment.TRAILING, 0, 105, Short.MAX_VALUE)
                            .addComponent(dnaCombo, javax.swing.GroupLayout.Alignment.TRAILING, 0, 105, Short.MAX_VALUE)
                            .addComponent(padSpinner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(padSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(padLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(dnaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dnaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(proteinCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(proteinLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tagCheckbox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Colour options:"));

        bColors.setText("Customise Tablet Colours");

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bColors)
                .addContainerGap(220, Short.MAX_VALUE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bColors)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bColors;
    private javax.swing.JComboBox<String> dnaCombo;
    private javax.swing.JLabel dnaLabel;
    private javax.swing.JLabel padLabel;
    private javax.swing.JSpinner padSpinner;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JComboBox<String> proteinCombo;
    private javax.swing.JLabel proteinLabel;
    private javax.swing.JCheckBox tagCheckbox;
    // End of variables declaration//GEN-END:variables
}