package tablet.gui.dialog;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

import tablet.gui.*;

import scri.commons.gui.*;

public class HuttonDialogNB extends javax.swing.JPanel implements ActionListener
{
	private static ImageIcon logo = Icons.getIcon("HUTTONDIALOG");

    /** Creates new form HuttonDialogNB */
    public HuttonDialogNB()
	{
		initComponents();
		link1.addActionListener(this);
		link2.addActionListener(this);
		link3.addActionListener(this);

		if (SystemUtils.isWindows() == false)
		{
			jLabel1.setFont(new java.awt.Font("Dialog", 1, 16));
			jLabel2.setFont(new java.awt.Font("Dialog", 1, 16));
			jLabel3.setFont(new java.awt.Font("Dialog", 2, 12));

			link1.setFont(new java.awt.Font("Dialog", 0, 12));
			link2.setFont(new java.awt.Font("Dialog", 0, 12));
			link3.setFont(new java.awt.Font("Dialog", 2, 12));
		}
    }

//	@Override
//	public Dimension getPreferredSize()
//	{
//		return new Dimension(790, 558);
//	}

	@Override
	public void paintComponent(Graphics graphics)
	{
		super.paintComponent(graphics);

		Graphics2D g = (Graphics2D) graphics;

		int w = getWidth();
		int h = getHeight();

		g.drawImage(logo.getImage(), 0, 0, w, h, null);
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        link1 = new scri.commons.gui.matisse.HyperLinkLabel();
        link2 = new scri.commons.gui.matisse.HyperLinkLabel();
        link3 = new scri.commons.gui.matisse.HyperLinkLabel();

        setMinimumSize(new java.awt.Dimension(790, 558));
        setPreferredSize(new java.awt.Dimension(790, 558));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Important News");

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18));
        jLabel2.setForeground(new java.awt.Color(134, 32, 116));
        jLabel2.setText("<html>On the 1st of April 2011 SCRI became part of The James Hutton Institute.</html>");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel3.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        jLabel3.setText("<html>Tablet will continue to be developed by the same Plant Bioinformatics Group as before. Please note that our primary URL will now be:</html>");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        link1.setForeground(new java.awt.Color(68, 106, 156));
        link1.setText("Click here for more information");
        link1.setFont(new java.awt.Font("Calibri", 0, 14));

        link2.setForeground(new java.awt.Color(68, 106, 156));
        link2.setText("Click here to close");
        link2.setFont(new java.awt.Font("Calibri", 0, 14));

        link3.setForeground(new java.awt.Color(68, 106, 156));
        link3.setText("http://bioinf.hutton.ac.uk");
        link3.setFont(new java.awt.Font("Calibri", 2, 14));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(563, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(link3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(link2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(link1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(link3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(link1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(link2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(230, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private scri.commons.gui.matisse.HyperLinkLabel link1;
    private scri.commons.gui.matisse.HyperLinkLabel link2;
    private scri.commons.gui.matisse.HyperLinkLabel link3;
    // End of variables declaration//GEN-END:variables

	@Override
	public void actionPerformed(ActionEvent e)
	{
		if (e.getSource() == link1)
			TabletUtils.visitURL("http://www.hutton.ac.uk/about");

		else if (e.getSource() == link2)
		{
			Container parent = getParent();
			while (parent instanceof JDialog == false)
				parent = parent.getParent();
			((JDialog)parent).setVisible(false);
		}

		else if (e.getSource() == link3)
			TabletUtils.visitURL("http://bioinf.hutton.ac.uk");
	}

}
