package tablet.gui.dialog;

import java.awt.*;
import javax.swing.*;
import scri.commons.gui.*;

public class NBImportAssemblyPanel extends javax.swing.JPanel
{

    /** Creates new form NBImportAssembly */
    public NBImportAssemblyPanel(ImportAssemblyDialog parent)
    {
	    initComponents();

	    assemblyComboBox.addItemListener(parent);

	    RB.setText(assemblyLabel, "gui.dialog.NBImportAssembly.assembly");
	    //RB.setText(fileLabel1, "gui.dialog.NBImportAssembly.fileType");
	    setBackground(Color.white);
	    setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        assemblyComboBox = new javax.swing.JComboBox();
        assemblyLabel = new javax.swing.JLabel();

        assemblyComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ACE", "AFG", "SOAP" }));
        assemblyComboBox.setMinimumSize(new java.awt.Dimension(80, 20));
        assemblyComboBox.setPreferredSize(new java.awt.Dimension(80, 20));

        assemblyLabel.setLabelFor(assemblyComboBox);
        assemblyLabel.setText("Assembly type");
        assemblyLabel.setPreferredSize(new java.awt.Dimension(94, 14));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(assemblyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(assemblyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assemblyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(assemblyComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JComboBox assemblyComboBox;
    private javax.swing.JLabel assemblyLabel;
    // End of variables declaration//GEN-END:variables

}
