// Copyright 2009 Plant Bioinformatics Group, SCRI. All rights reserved.
// Use is subject to the accompanying licence terms.

package tablet.gui.dialog;

import java.awt.*;
import java.util.*;
import javax.swing.*;

import tablet.gui.Prefs;

import scri.commons.gui.*;

class NBImportAssemblyMaqPanel extends javax.swing.JPanel
{
    LinkedList<String> recentFilesMaq = new LinkedList<String>();
    LinkedList<String> recentFilesFastq = new LinkedList<String>();

	public NBImportAssemblyMaqPanel(ImportAssemblyDialog parent)
	{
		initComponents();

		setBackground(Color.white);
		setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));

		RB.setText(bBrowse1, "gui.text.browse");
		RB.setText(bBrowse2, "gui.text.browse");
		RB.setText(soapLabel, "gui.dialog.NBImportAssemblyMaqPanel.maqLabel");
		RB.setText(fastaLabel, "gui.dialog.NBImportAssemblyMaqPanel.fastqLabel");

		// Parse out the tab-delimited list of files
		StringTokenizer st = new StringTokenizer(Prefs.maqRecentDocs, "\t");
		while (st.hasMoreTokens())
			recentFilesMaq.add(st.nextToken());

		st = new StringTokenizer(Prefs.fastqRecentDocs, "\t");
		while (st.hasMoreTokens())
			recentFilesFastq.add(st.nextToken());

		parent.updateComboBox(null, maqComboBox, recentFilesMaq);
		parent.updateComboBox(null, fastqComboBox, recentFilesFastq);

		bBrowse1.addActionListener(parent);
		bBrowse2.addActionListener(parent);
		maqComboBox.addActionListener(parent);
		fastqComboBox.addActionListener(parent);
	}

	String[] getFilenames()
	{
		return new String[] {
			recentFilesMaq.get(0), recentFilesFastq.get(0) };
	}

	boolean isOK()
	{
		// Save the list back to the preferences
		Prefs.maqRecentDocs = "";
		for (String str: recentFilesMaq)
			Prefs.maqRecentDocs += str + "\t";

		Prefs.fastqRecentDocs = "";
		for (String str: recentFilesFastq)
			Prefs.fastqRecentDocs += str + "\t";

		return maqComboBox.getSelectedItem() != null &&
			fastqComboBox.getSelectedItem() != null;
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        soapLabel = new javax.swing.JLabel();
        maqComboBox = new javax.swing.JComboBox();
        bBrowse1 = new javax.swing.JButton();
        fastaLabel = new javax.swing.JLabel();
        fastqComboBox = new javax.swing.JComboBox();
        bBrowse2 = new javax.swing.JButton();

        soapLabel.setLabelFor(maqComboBox);
        soapLabel.setText("Maq input file:");

        maqComboBox.setEditable(true);

        bBrowse1.setText("Browse...");

        fastaLabel.setLabelFor(fastqComboBox);
        fastaLabel.setText("FASTQ input file:");

        fastqComboBox.setEditable(true);

        bBrowse2.setText("Browse...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(soapLabel)
                    .addComponent(fastaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(maqComboBox, 0, 248, Short.MAX_VALUE)
                    .addComponent(fastqComboBox, 0, 248, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bBrowse1)
                    .addComponent(bBrowse2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soapLabel)
                    .addComponent(maqComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBrowse1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fastaLabel)
                    .addComponent(fastqComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBrowse2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton bBrowse1;
    javax.swing.JButton bBrowse2;
    private javax.swing.JLabel fastaLabel;
    javax.swing.JComboBox fastqComboBox;
    javax.swing.JComboBox maqComboBox;
    private javax.swing.JLabel soapLabel;
    // End of variables declaration//GEN-END:variables

}