package tablet.gui.viewer;

import java.awt.*;
import java.awt.event.*;
import java.text.*;
import javax.swing.*;
import javax.swing.event.*;

import tablet.gui.*;
import tablet.gui.viewer.colors.*;

import scri.commons.gui.*;

class NBStatusPanel extends JPanel
{
	private DecimalFormat d1 = new DecimalFormat("0.0");
	private DecimalFormat d3 = new DecimalFormat("0.000");

	private AssemblyPanel aPanel;

	NBStatusPanel(AssemblyPanel aPanel)
	{
		this.aPanel = aPanel;

		initComponents();

		output1.setForeground(Color.red);
		output1.setText(" ");
		output2.setForeground(Color.red);
		output2.setText(" ");
		output3.setForeground(Color.red);
		output3.setText(" ");

		setBorder(BorderFactory.createEmptyBorder(10, 0, 0, 0));
		setForMainUse();
	}

	void setForMainUse()
	{
	}

	void setLabels(String str1, String str2, String str3)
	{
		if (str1 != null)
			output1.setText(str1);
		else
			output1.setText(" ");

		if (str2 != null)
			output2.setText(str2);
		else
			output2.setText(" ");

		if (str3 != null)
			output3.setText(str3);
		else
			output3.setText(" ");
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new javax.swing.JLabel();
        output1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        output2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        output3 = new javax.swing.JLabel();

        label1.setText("Label 1:");

        output1.setText("<>");

        label2.setText("Label 2:");

        output2.setText("<>");

        label3.setText("Label 3:");

        output3.setText("<>");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(label3)
                    .add(label1)
                    .add(label2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(output3)
                    .add(output2)
                    .add(output1))
                .addContainerGap(479, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(label1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(label2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(label3))
                    .add(layout.createSequentialGroup()
                        .add(output1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(output2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(output3)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    javax.swing.JLabel output1;
    javax.swing.JLabel output2;
    javax.swing.JLabel output3;
    // End of variables declaration//GEN-END:variables
}