/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NBFeaturesPanelControls.java
 *
 * Created on 14-Sep-2009, 16:21:40
 */

package tablet.gui;

import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import scri.commons.gui.RB;

/**
 *
 * @author gsteph
 */
public class NBFeaturesPanelControls extends javax.swing.JPanel implements DocumentListener
{

	private FeaturesPanel panel;

    /** Creates new form NBFeaturesPanelControls */
    public NBFeaturesPanelControls(FeaturesPanel panel)
	{
        initComponents();

		this.panel = panel;

		// i18n text
		RB.setText(filterLabel, "gui.NBFeaturesPanelControls.filterLabel");

		filterText.getDocument().addDocumentListener(this);
    }

	public void changedUpdate(DocumentEvent e)
		{ filter(); }

	public void insertUpdate(DocumentEvent e)
		{ filter(); }

	public void removeUpdate(DocumentEvent e)
		{ filter(); }

	private void filter()
	{
		RowFilter<FeaturesTableModel, Object> rf = null;

		try
		{
			rf = RowFilter.regexFilter(filterText.getText(), 0);
		}
		catch (Exception e)
		{
			System.out.println(e);
		}

		panel.setTableFilter(rf);
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filterLabel = new javax.swing.JLabel();
        filterText = new javax.swing.JTextField();

        filterLabel.setLabelFor(filterText);
        filterLabel.setText("Filter by type:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(filterLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filterText, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filterLabel)
                    .addComponent(filterText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel filterLabel;
    private javax.swing.JTextField filterText;
    // End of variables declaration//GEN-END:variables

}
