package tablet.gui;

import java.awt.event.*;
import javax.swing.*;
import scri.commons.gui.*;

public class NBFindPanelControls extends javax.swing.JPanel
{
	private FindPanel panel;

    /** Creates new form NBFindPanel */
    public NBFindPanelControls(final FindPanel panel)
	{
        initComponents();

		this.panel = panel;

		findLabel.setText(RB.getString("gui.NBFindPanelControls.findLabel"));
		resultsLabel.setText(RB.format("gui.NBFindPanelControls.resultsLabel", 0));
		RB.setText(helpLabel, "gui.NBFindPanelControls.helpLabel");

		findCombo.setHistory(Prefs.recentSearches);

		DefaultComboBoxModel model = new DefaultComboBoxModel();
		model.addElement(RB.getString("gui.NBFindPanelControls.currentContig"));
		model.addElement(RB.getString("gui.NBFindPanelControls.allContigs"));

		findInCombo.setModel(model);

		findInCombo.setSelectedIndex(Prefs.guiFindPanelSelectedIndex);

		findCombo.setPrototypeDisplayValue(25);

		bFind.setText("");
		bFind.setIcon(Icons.getIcon("FIND"));

		bFind.addActionListener(panel);
		if(!SystemUtils.isMacOS())
			bFind.setBorder(BorderFactory.createEmptyBorder(0, 11, 0, 11));

		table.getTableHeader().setReorderingAllowed(false);
		table.getSelectionModel().setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
		table.getSelectionModel().addListSelectionListener(panel);

		RB.setText(checkUseRegex, "gui.NBFindPanelControls.checkUseRegex");
		checkUseRegex.setSelected(Prefs.guiRegexSearching);
		checkUseRegex.addActionListener(panel);


		findCombo.getEditor().getEditorComponent().addKeyListener(new KeyAdapter() {
		public void keyReleased(KeyEvent e)
		{
			if(e.getKeyCode() == KeyEvent.VK_ENTER)
				panel.runSearch();
		}});

		helpLabel.setIcon(Icons.getIcon("WEB"));
		helpLabel.addActionListener(panel);
    }

	public void toggleComponentEnabled(boolean visible)
	{
		bFind.setEnabled(visible);
		findCombo.setEnabled(visible);
		findInCombo.setEnabled(visible);
		findLabel.setEnabled(visible);
		resultsLabel.setEnabled(visible);
		table.setEnabled(visible);
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        findLabel = new javax.swing.JLabel();
        findCombo = new scri.commons.gui.matisse.HistoryComboBox();
        findInCombo = new javax.swing.JComboBox();
        resultsLabel = new javax.swing.JLabel();
        bFind = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new JTable() {
            public String getToolTipText(MouseEvent e) {
                return panel.getTableToolTip(e);
            }
        };
        helpLabel = new scri.commons.gui.matisse.HyperLinkLabel();
        checkUseRegex = new javax.swing.JCheckBox();

        findLabel.setLabelFor(findCombo);
        findLabel.setText("Search for reads by name:");

        findInCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findInComboActionPerformed(evt);
            }
        });

        resultsLabel.setText("Results:");

        bFind.setText("Find");
        bFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFindActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table);

        helpLabel.setForeground(new java.awt.Color(68, 106, 156));
        helpLabel.setText("Get help with searching");

        checkUseRegex.setText("Use Java regular expressions");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkUseRegex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(findLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(findCombo, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bFind, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(findInCombo, 0, 167, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(helpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultsLabel)
                .addContainerGap(138, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(findLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(findCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bFind))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(findInCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkUseRegex)
                .addGap(18, 18, 18)
                .addComponent(resultsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(helpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bFind, findCombo, findInCombo});

    }// </editor-fold>//GEN-END:initComponents

	private void findInComboActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_findInComboActionPerformed
	{//GEN-HEADEREND:event_findInComboActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_findInComboActionPerformed

	private void bFindActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bFindActionPerformed
	{//GEN-HEADEREND:event_bFindActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_bFindActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bFind;
    javax.swing.JCheckBox checkUseRegex;
    public scri.commons.gui.matisse.HistoryComboBox findCombo;
    public javax.swing.JComboBox findInCombo;
    public javax.swing.JLabel findLabel;
    scri.commons.gui.matisse.HyperLinkLabel helpLabel;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel resultsLabel;
    public javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

}
