package tablet.gui;

import java.awt.*;
import java.awt.image.*;
import javax.swing.*;

import tablet.gui.viewer.colors.*;

public class ReadGroupsPanelNB extends JPanel
{
	DefaultListModel model;

	/** Creates new form ReadGroupsPanelNB */
	public ReadGroupsPanelNB(ReadGroupsPanel panel)
	{
		initComponents();

		colourList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
		colourList.setCellRenderer(new ColorListRenderer());

		model = new DefaultListModel();
		colourList.setModel(model);

		resetLabel.addActionListener(panel);
	}

	// Update the model for the currently displayed contig.
	void updateModel()
	{
		model.clear();

		if (ReadGroupScheme.getColourInfos() != null && ReadGroupScheme.getColourInfos().length > 0)
			for (ReadGroupScheme.ColorInfo info: ReadGroupScheme.getColourInfos())
				model.addElement(info);
	}

	static class ColorListRenderer extends DefaultListCellRenderer
	{
		// Set the attributes of the class and return a reference
		@Override
		public Component getListCellRendererComponent(JList list, Object o,
				int i, boolean iss, boolean chf)
		{
			super.getListCellRendererComponent(list, o, i, iss, chf);

			ReadGroupScheme.ColorInfo info = (ReadGroupScheme.ColorInfo) o;

			// Set the text
			setText(info.name);

			// Set the icon
			BufferedImage image = new BufferedImage(20, 10, BufferedImage.TYPE_INT_RGB);
			Graphics2D g = image.createGraphics();

			g.setColor(info.color);
			g.fillRect(0, 0, 20, 10);
			g.setColor(Color.black);
			g.drawRect(0, 0, 20, 10);
			g.dispose();

			setIcon(new ImageIcon(image));

			return this;
		}

		@Override
		public Insets getInsets(Insets i)
			{ return new Insets(0, 3, 0, 0); }
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        readGroupLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        colourList = new javax.swing.JList();
        resetLabel = new scri.commons.gui.matisse.HyperLinkLabel();

        readGroupLabel.setText("Read groups colors: 0");

        jScrollPane1.setViewportView(colourList);

        resetLabel.setForeground(new java.awt.Color(68, 106, 156));
        resetLabel.setText("Reset read groups");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(readGroupLabel)
                .addContainerGap(286, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(302, Short.MAX_VALUE)
                .addComponent(resetLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(readGroupLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resetLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JList colourList;
    private javax.swing.JScrollPane jScrollPane1;
    javax.swing.JLabel readGroupLabel;
    scri.commons.gui.matisse.HyperLinkLabel resetLabel;
    // End of variables declaration//GEN-END:variables

}
