// Copyright 2009-2014 Information & Computational Sciences, JHI. All rights
// reserved. Use is subject to the accompanying licence terms.

package tablet.gui;

import tablet.data.auxiliary.*;

class ReadGroupsLabelNB extends javax.swing.JPanel
{
	ReadGroupsLabelNB()
	{
		initComponents();

		clearLabels();
	}

	void clearLabels()
	{
		setLabels(new ReadGroup());
	}

	void setLabels(ReadGroup readGroup)
	{
		id.setText(readGroup.getID());
		id.setVisible(id.getText().length() > 0);
		labelID.setVisible(id.isVisible());


		cn.setText(readGroup.getCN());
		cn.setVisible(cn.getText().length() > 0);
		labelCN.setVisible(cn.isVisible());

		ds.setText(readGroup.getDS());
		ds.setVisible(ds.getText().length() > 0);
		labelDS.setVisible(ds.isVisible());

		dt.setText(readGroup.getDT());
		dt.setVisible(dt.getText().length() > 0);
		labelDT.setVisible(dt.isVisible());

		fo.setText(readGroup.getFO());
		fo.setVisible(fo.getText().length() > 0);
		labelFO.setVisible(fo.isVisible());

		ks.setText(readGroup.getKS());
		ks.setVisible(ks.getText().length() > 0);
		labelKS.setVisible(ks.isVisible());

		lb.setText(readGroup.getLB());
		lb.setVisible(lb.getText().length() > 0);
		labelLB.setVisible(lb.isVisible());

		pg.setText(readGroup.getPG());
		pg.setVisible(pg.getText().length() > 0);
		labelPG.setVisible(pg.isVisible());

		pi.setText(readGroup.getPI());
		pi.setVisible(pi.getText().length() > 0);
		labelPI.setVisible(pi.isVisible());

		pl.setText(readGroup.getPL());
		pl.setVisible(pl.getText().length() > 0);
		labelPL.setVisible(pl.isVisible());

		pu.setText(readGroup.getPU());
		pu.setVisible(pu.getText().length() > 0);
		labelPU.setVisible(pu.isVisible());

		sm.setText(readGroup.getSM());
		sm.setVisible(sm.getText().length() > 0);
		labelSM.setVisible(sm.isVisible());
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        id = new javax.swing.JLabel();
        labelCN = new javax.swing.JLabel();
        cn = new javax.swing.JLabel();
        labelDS = new javax.swing.JLabel();
        ds = new javax.swing.JLabel();
        labelDT = new javax.swing.JLabel();
        dt = new javax.swing.JLabel();
        pi = new javax.swing.JLabel();
        labelPI = new javax.swing.JLabel();
        pg = new javax.swing.JLabel();
        sm = new javax.swing.JLabel();
        labelPG = new javax.swing.JLabel();
        lb = new javax.swing.JLabel();
        labelLB = new javax.swing.JLabel();
        pl = new javax.swing.JLabel();
        labelKS = new javax.swing.JLabel();
        labelPU = new javax.swing.JLabel();
        ks = new javax.swing.JLabel();
        labelFO = new javax.swing.JLabel();
        pu = new javax.swing.JLabel();
        labelSM = new javax.swing.JLabel();
        fo = new javax.swing.JLabel();
        labelPL = new javax.swing.JLabel();
        labelID = new javax.swing.JLabel();

        id.setForeground(new java.awt.Color(255, 0, 0));
        id.setText("  ");

        labelCN.setText("CN:");

        cn.setForeground(new java.awt.Color(255, 0, 0));
        cn.setText("  ");

        labelDS.setText("DS:");

        ds.setForeground(new java.awt.Color(255, 0, 0));
        ds.setText("  ");

        labelDT.setText("DT:");

        dt.setForeground(new java.awt.Color(255, 0, 0));
        dt.setText("  ");

        pi.setForeground(new java.awt.Color(255, 0, 0));
        pi.setText("  ");

        labelPI.setText("PI:");

        pg.setForeground(new java.awt.Color(255, 0, 0));
        pg.setText("  ");

        sm.setForeground(new java.awt.Color(255, 0, 0));
        sm.setText("  ");

        labelPG.setText("PG:");

        lb.setForeground(new java.awt.Color(255, 0, 0));
        lb.setText("  ");

        labelLB.setText("LB:");

        pl.setForeground(new java.awt.Color(255, 0, 0));
        pl.setText("  ");

        labelKS.setText("KS:");

        labelPU.setText("PU:");

        ks.setForeground(new java.awt.Color(255, 0, 0));
        ks.setText("  ");

        labelFO.setText("FO:");

        pu.setForeground(new java.awt.Color(255, 0, 0));
        pu.setText("  ");

        labelSM.setText("SM:");

        fo.setForeground(new java.awt.Color(255, 0, 0));
        fo.setText("  ");

        labelPL.setText("PL:");

        labelID.setText("ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCN)
                    .addComponent(labelDS)
                    .addComponent(labelDT)
                    .addComponent(labelFO)
                    .addComponent(labelKS)
                    .addComponent(labelLB)
                    .addComponent(labelPG)
                    .addComponent(labelPI)
                    .addComponent(labelPL)
                    .addComponent(labelPU)
                    .addComponent(labelSM)
                    .addComponent(labelID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fo)
                    .addComponent(dt)
                    .addComponent(ks)
                    .addComponent(pg)
                    .addComponent(lb)
                    .addComponent(sm)
                    .addComponent(pl)
                    .addComponent(pi)
                    .addComponent(pu)
                    .addComponent(id)
                    .addComponent(cn)
                    .addComponent(ds))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelID)
                    .addComponent(id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCN)
                    .addComponent(cn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDS)
                    .addComponent(ds))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDT)
                    .addComponent(dt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFO)
                    .addComponent(fo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKS)
                    .addComponent(ks))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLB)
                    .addComponent(lb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPG)
                    .addComponent(pg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPI)
                    .addComponent(pi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPL)
                    .addComponent(pl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPU)
                    .addComponent(pu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSM)
                    .addComponent(sm))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JLabel cn;
    javax.swing.JLabel ds;
    javax.swing.JLabel dt;
    javax.swing.JLabel fo;
    javax.swing.JLabel id;
    javax.swing.JLabel ks;
    private javax.swing.JLabel labelCN;
    private javax.swing.JLabel labelDS;
    private javax.swing.JLabel labelDT;
    private javax.swing.JLabel labelFO;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel labelKS;
    private javax.swing.JLabel labelLB;
    private javax.swing.JLabel labelPG;
    private javax.swing.JLabel labelPI;
    private javax.swing.JLabel labelPL;
    private javax.swing.JLabel labelPU;
    private javax.swing.JLabel labelSM;
    javax.swing.JLabel lb;
    javax.swing.JLabel pg;
    javax.swing.JLabel pi;
    javax.swing.JLabel pl;
    javax.swing.JLabel pu;
    javax.swing.JLabel sm;
    // End of variables declaration//GEN-END:variables
}