// Copyright 2009-2010 Plant Bioinformatics Group, SCRI. All rights reserved.
// Use is subject to the accompanying licence terms.

package tablet.gui;

import java.awt.event.*;
import javax.swing.*;
import scri.commons.gui.*;

public class NBFindPanelControls extends javax.swing.JPanel
{
	private FindPanel panel;

    /** Creates new form NBFindPanel */
    public NBFindPanelControls(final FindPanel panel)
	{
        initComponents();

		this.panel = panel;

		// Setup the various visual components and fill with the correct data / options
		searchTypeCombo.addItem(RB.getString("gui.NBFindPanelControls.findLabel1"));
		searchTypeCombo.addItem(RB.getString("gui.NBFindPanelControls.findLabel2"));
		searchTypeCombo.setSelectedIndex(Prefs.guiFindPanelSearchType);
		resultsLabel.setText(RB.format("gui.NBFindPanelControls.resultsLabel", 0));
		RB.setText(helpLabel, "gui.NBFindPanelControls.helpLabel");
		RB.setText(label, "gui.NBFindPanelControls.label");

		findCombo.setHistory(Prefs.recentSearches);

		DefaultComboBoxModel model = new DefaultComboBoxModel();
		model.addElement(RB.getString("gui.NBFindPanelControls.currentContig"));
		model.addElement(RB.getString("gui.NBFindPanelControls.allContigs"));

		findInCombo.setModel(model);
		findInCombo.setSelectedIndex(Prefs.guiFindPanelSelectedIndex);

		findCombo.setPrototypeDisplayValue(25);

		bFind.setText("");
		bFind.setIcon(Icons.getIcon("FIND"));

		bFind.addActionListener(panel);

		if(!SystemUtils.isMacOS())
			bFind.setBorder(BorderFactory.createEmptyBorder(0, 11, 0, 11));

		// Setup the table with the desired properties
		table.getTableHeader().setReorderingAllowed(false);
		table.getSelectionModel().setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
		table.getSelectionModel().addListSelectionListener(panel);

		RB.setText(checkUseRegex, "gui.NBFindPanelControls.checkUseRegex");
		checkUseRegex.setSelected(Prefs.guiRegexSearching);
		checkUseRegex.addActionListener(panel);

		// Setup a keyboard listener on  the findCombo combo box. This was to allow
		// the user to hit return from the combo box to run the search.
		findCombo.getEditor().getEditorComponent().addKeyListener(new KeyAdapter() {
		public void keyPressed(KeyEvent e)
		{
			if(e.getKeyCode() == KeyEvent.VK_ENTER)
				panel.runSearch();
		}});

		helpLabel.setIcon(Icons.getIcon("WEB"));
		helpLabel.addActionListener(panel);

		searchTypeCombo.addActionListener(panel);
    }

	/**
	 * Toggle which components are enabled to ensure that the correct components
	 * are enabled / disabled at any given time. 
	 */
	public void toggleComponentEnabled(boolean enabled)
	{
		label.setEnabled(enabled);
		bFind.setEnabled(enabled);
		findCombo.setEnabled(enabled);
		findInCombo.setEnabled(enabled);
		searchTypeCombo.setEnabled(enabled);
		resultsLabel.setEnabled(enabled);
		table.setEnabled(enabled);
		if(searchTypeCombo.getSelectedItem().equals(RB.getString("gui.NBFindPanelControls.findLabel2")))
			checkUseRegex.setEnabled(false);
		else
			checkUseRegex.setEnabled(enabled);
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        findCombo = new scri.commons.gui.matisse.HistoryComboBox();
        findInCombo = new javax.swing.JComboBox();
        resultsLabel = new javax.swing.JLabel();
        bFind = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new JTable() {
            public String getToolTipText(MouseEvent e) {
                return panel.getTableToolTip(e);
            }
        };
        helpLabel = new scri.commons.gui.matisse.HyperLinkLabel();
        checkUseRegex = new javax.swing.JCheckBox();
        searchTypeCombo = new javax.swing.JComboBox();
        label = new javax.swing.JLabel();

        resultsLabel.setText("Results:");

        bFind.setText("Find");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table);

        helpLabel.setForeground(new java.awt.Color(68, 106, 156));
        helpLabel.setText("Get help with searching");

        checkUseRegex.setText("Use Java regular expressions");

        label.setText("Search:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(helpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label)
                .addContainerGap(140, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkUseRegex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(findCombo, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bFind, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(findInCombo, 0, 167, Short.MAX_VALUE)
                    .addComponent(searchTypeCombo, 0, 167, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultsLabel)
                .addContainerGap(138, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(findCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bFind))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(findInCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkUseRegex)
                .addGap(18, 18, 18)
                .addComponent(resultsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(helpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bFind, findCombo, findInCombo});

    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bFind;
    javax.swing.JCheckBox checkUseRegex;
    public scri.commons.gui.matisse.HistoryComboBox findCombo;
    public javax.swing.JComboBox findInCombo;
    scri.commons.gui.matisse.HyperLinkLabel helpLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label;
    public javax.swing.JLabel resultsLabel;
    javax.swing.JComboBox searchTypeCombo;
    public javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

}