package tablet.gui;

import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

import scri.commons.gui.*;

class NBFeaturesPanelControls extends JPanel
	implements ActionListener, DocumentListener
{
	private FeaturesPanel panel;

    /** Creates new form NBFeaturesPanelControls */
    public NBFeaturesPanelControls(FeaturesPanel panel)
	{
        initComponents();

		this.panel = panel;

		// i18n text
		RB.setText(filterLabel, "gui.NBFeaturesPanelControls.filterLabel");
		RB.setText(checkPadded, "gui.NBFeaturesPanelControls.checkPadded");
		checkPadded.setToolTipText(RB.getString("gui.NBFeaturesPanelControls.checkPaddedTooltip"));

		checkPadded.setSelected(Prefs.guiFeaturesArePadded);

		filterText.getDocument().addDocumentListener(this);
		checkPadded.addActionListener(this);

		table.getTableHeader().setReorderingAllowed(false);
		table.getSelectionModel().setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
		table.getSelectionModel().addListSelectionListener(panel);
    }

	public void changedUpdate(DocumentEvent e)
		{ filter(); }

	public void insertUpdate(DocumentEvent e)
		{ filter(); }

	public void removeUpdate(DocumentEvent e)
		{ filter(); }

	private void filter()
	{
		RowFilter<FeaturesTableModel, Object> rf = null;

		try
		{
			rf = RowFilter.regexFilter(filterText.getText().toUpperCase(), 0);
		}
		catch (Exception e)
		{
			System.out.println(e);
		}

		panel.setTableFilter(rf);
	}

	public void actionPerformed(ActionEvent e)
	{
		if (Prefs.guiWarnOnPaddedFeatureToggle)
		{
			String msg = RB.getString("gui.NBFeaturesPanelControls.checkMessage");
			JCheckBox checkbox = new JCheckBox();
			RB.setText(checkbox, "gui.NBFeaturesPanelControls.checkWarning");

			TaskDialog.info(msg, RB.getString("gui.text.close"), checkbox);

			Prefs.guiWarnOnPaddedFeatureToggle = !checkbox.isSelected();
		}

		Prefs.guiFeaturesArePadded = checkPadded.isSelected();
	}

	public void toggleComponentEnabled(boolean enabled)
	{
		checkPadded.setEnabled(enabled);
		filterLabel.setEnabled(enabled);
		filterText.setEnabled(enabled);
		featuresLabel.setEnabled(enabled);
		table.setEnabled(enabled);
	}

	public void nextFeature()
	{
		if(table.getSelectedRow() < table.getRowCount()-1)
			table.setRowSelectionInterval(table.getSelectedRow()+1, table.getSelectedRow()+1);

		table.scrollRectToVisible(table.getCellRect(table.getSelectedRow(), table.getSelectedColumn(), true));
	}

	public void prevFeature()
	{
		if(table.getSelectedRow() == -1)
			table.setRowSelectionInterval(table.getRowCount()-1, table.getRowCount()-1);
		else if(table.getSelectedRow() > 0)
			table.setRowSelectionInterval(table.getSelectedRow()-1, table.getSelectedRow()-1);

		table.scrollRectToVisible(table.getCellRect(table.getSelectedRow(), table.getSelectedColumn(), true));
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filterLabel = new javax.swing.JLabel();
        filterText = new javax.swing.JTextField();
        checkPadded = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        featuresLabel = new javax.swing.JLabel();

        filterLabel.setLabelFor(filterText);
        filterLabel.setText("Filter by type:");

        checkPadded.setText("Feature values are padded");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table);

        featuresLabel.setText("Features (0):");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(featuresLabel)
                .addContainerGap(326, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkPadded)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(filterLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filterText, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(featuresLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filterLabel)
                    .addComponent(filterText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkPadded)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkPadded;
    public javax.swing.JLabel featuresLabel;
    private javax.swing.JLabel filterLabel;
    private javax.swing.JTextField filterText;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

}
